import '../styles/globals.css';

import type { AppProps } from 'next/app';
import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <div className="bg-gray-900 text-white">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="stylesheet"
                    href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-gray-900 min-h-screen relative">
                <Navbar />
                <Component {...pageProps} />
            </main>

            <Footer />
        </div>
    );
}

export default MyApp;
